### PR TITLE
Inspector update

### PR DESCRIPTION
**Pull request by Tmilly**
Everything on the inspector checklist complete EXCEPT for flipping the direction of the polygon

### CODE REVIEW

**Comment by Tmilly** [comment]
Just realized some more code was added to master an hour or two before this so we'll have to merge these updates and Save update together later

**Review by tommy-russoniello — CHANGES_REQUESTED** [review]
- This must be rebased to have Quinn's save update changes in it. Merging this in its current state will erase all of the save functionality.
- Changing line types needs to use Quinn's methods for writing objects as strings. There is a lot more to relationship lines than start and stop and Quinn has already figured out the hard parts on how to do this.
- There should be apply buttons for each of an objects fields (except x an y coordinates can just be one). Especially for the different text fields in ClassBoxes. A big reason for this is to keep the undo/redo stacks coherent.
- If can't make these changes/need help, let us know asap. The changes are simple but pretty important.

**Comment by Tmilly** [comment]
Yeah i worked with what i had last night and the day before, i cant make changes today due to my data mining semester project that i have to work on all day today. If you want to look at it and update it to work with Quinns update that would be great, i cant sink another 5 hours in again.. hopefully not all this work I did went to waste. Atleast the fxml code can remain the same

**Comment by tommy-russoniello** [comment]
replaced with gh-42

**Pull request closed without merging**
