### PR TITLE
Scroll and Export Implementation

### PR DESCRIPTION
**Pull request by scarroll142**
Main Features:
-Pane can now be scrolled
-Contents of the current pane can be exported to a pdf.

Minor Features:
-Removed some unused imports
-Added some comments
-Nodes can no longer be dragged onto menu bar

### CODE REVIEW

**Review by tommy-russoniello — APPROVED** [review]

**Review by tommy-russoniello — APPROVED** [review]
DOUBLE APPROVE

**Review by tommy-russoniello — APPROVED** [review]
TRIPLE APPROVE?!?!?!????!?1123

**Review by tommy-russoniello — APPROVED** [review]
WORLD'S FIRST **Q U A D R U P L E** APPROVE!!!!

**Review by quinnminnich — APPROVED** [review]
Nice job!

**Review by Tmilly — APPROVED** [review]
Noice!

**Pull request merged**
