### PR TITLE
Line Updates

### PR DESCRIPTION
**Pull request by tommy-russoniello**
### MAJOR CHANGES ###
- Add all line types (association, aggregation, composition, dependency, and generalization) with full adding, deleting, dragging, and undo/redo support. All classes are under the new `Relationship` class which extends `UMLConnector`. Relationship and all new line type files are all fully documented.
- Add relationship quantifiers to relationship lines (still need inspector stuff to make this feature accessible though). Also added action classes for changing their text.
- Add line segmenting through pivots (new `Pivot` and `Segment` classes). Segmenting is fully draggable, deletable, undoable and redoable.
- Add Note class (fully documented).

**MINOR CHANGES**
- Add javadoc file header to all files (still need a lot more documentation overall though).
- Add `refresh()` method to controller that resets all lines. (can use at run time with ctrl/cmd-R).
- Rework `paneClick()` method as well as slightly modify `addObjects()` and `deleteObjects()`.
- Add `getSegment()` and `getPivot()` methods to controller for accessing the pivot/segment corresponding to given model.
- Improve `printState()` method.
- Change object builder buttons layout.
- Fixed bug with dragging handlers.
- Added `.DS_STORE` files to `.gitignore`.

### CODE REVIEW

**Review by scarroll142 — APPROVED** [review]
Looks good. Not sure if we want to have all those different types of mode though. We can easily change that though.

**Review by quinnminnich — APPROVED** [review]
Your work is awesome! I might suggest that instead of a different mode for each line, that we create one line mode, and then give the inspector the option of changing its type. I am excited to see you go over everything in more detail with us tomorrow.

**Comment by tommy-russoniello** [comment]
@quinnminnich, I left it as a separate mode for each because I didn't do any of the new inspector stuff to go along with my updates. I was thinking this is what @Tmilly could add. But yeah we can go over it more tomorrow.

**Review by Tmilly — APPROVED** [review]
Looks good

**Pull request merged**
