### PR TITLE
Action Objects

### PR DESCRIPTION
**Pull request by tommy-russoniello**
- Add undo/redo with action objects package
- Add highlighting for selected objects (`selectObjec()`, `deselectObject()`, `deselectAll()`, `deselectAllNodes()`, `deselectAllConnectors()` methods)
- Add dynamic resizing for class boxes
- Remove all static references to controller and replace with instance references (controller can now dynamically reference scene)
- Add undo/redo buttons to menu bar (plus ctrl/cmd Z and Y)
- Add `printState()` method for debugging (ctrl/cmd P)
- Make `deleteObject()` able to delete multiple objects in one call (renamed to `deleteObjects()`)
- Fix names where "circle" was used instead of "point" and "line" was used instead of "UMLConnector"
- Add hover action to UMLConnectors
- Clean up a lot of code

### CODE REVIEW

**Comment by tommy-russoniello** [comment]
Most of what I added does **not** have documentation, fyi.

**Review by scarroll142 — APPROVED** [review]
Best I've ever seen, Grade: 90%.

**Review by quinnminnich — APPROVED** [review]
Nice Job! This is really coming together now! Should I delete my pull request then?

**Comment by tommy-russoniello** [comment]
@quinnminnich If you think this PR adequately covers everything yours had then yes

**Pull request merged**
